name: FinTrack CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'

jobs:
  backend-checks:
    name: API - Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./apps/api/package-lock.json

      - run: npm ci
      - run: npm run lint || true
      - run: npx tsc --noEmit
      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: api-dist
          path: ./apps/api/dist
          retention-days: 7

  frontend-checks:
    name: Web - Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/web

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./apps/web/package-lock.json

      - run: npm ci
      - run: npm run lint || true
      - run: npx tsc --noEmit
      - run: npm run build
        env:
          VITE_API_URL: http://localhost:5000/api
          VITE_WS_URL: ws://localhost:5000

      - uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: ./apps/web/dist
          retention-days: 7

  ml-service-checks:
    name: ML - Lint & Syntax Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/ml

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: ./apps/ml/requirements.txt

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black

      - run: black --check app/ || true
      - run: flake8 app/ --max-line-length=120 --extend-ignore=E203,W503 || true
      - run: python -m py_compile app/**/*.py

  docker-build:
    name: Docker - Build Images
    runs-on: ubuntu-latest
    needs: [backend-checks, frontend-checks, ml-service-checks]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: false
          tags: fintrack-api:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v5
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          push: false
          tags: fintrack-web:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=http://localhost:5000/api
            VITE_WS_URL=ws://localhost:5000

      - uses: docker/build-push-action@v5
        with:
          context: ./apps/ml
          file: ./apps/ml/Dockerfile
          push: false
          tags: fintrack-ml:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

  security-scan:
    name: Security - Dependency Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - run: npm audit --audit-level=high || true
        working-directory: ./apps/api

      - run: npm audit --audit-level=high || true
        working-directory: ./apps/web

      - run: |
          pip install safety
          safety check -r requirements.txt || true
        working-directory: ./apps/ml
